name: "Sync GitHub to Azure Repos"

on:
  push:
    branches:
      - main

jobs:
  sync-azure:
    name: "Sync to Azure Repos"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Push to Azure Repos
        env:
          AZURE_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          git config user.name "GitHub Action Bot"
          git config user.email "miteshjamwal152@gmail.com"

          AZURE_REPO_URL="https://miteshjamwal152:${AZURE_PAT}@dev.azure.com/miteshjamwal152/mite_new_1/_git/pilot_1234"

          git remote add azure $AZURE_REPO_URL || git remote set-url azure $AZURE_REPO_URL
          git push azure main --force